# Generated by Django 4.0.4 on 2022-05-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0002_alter_student_idennum_alter_student_mopile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mopile',
            new_name='mobile',
        ),
    ]
