# Generated by Django 4.0.4 on 2022-05-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0003_rename_mopile_student_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sNo',
            field=models.IntegerField(default=0),
        ),
    ]
